# Generated by Django 3.0.6 on 2020-05-26 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
